server:
  port: 4001

spring:
  application:
    name: etl-dashboard-v2

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss

# Configuracoes ETL
etl:
  config:
    path: ${ETL_CONFIG_PATH:C:\bloko\Fundos - Documentos\00. Monitoramento\01. Rotinas\03. Arquivos Rotina\ETL}

logging:
  level:
    com.etl: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
